from django.db import models

class Metadata(models.Model):
        data_set_idx=models.AutoField(primary_key=True)
        data_set=models.CharField(max_length=150)
        version=models.CharField(max_length=150)
        media_url=models.CharField(max_length=150)
        cre_dt=models.DateTimeField( auto_now=True)
        ado_result=models.CharField(max_length=150)
        bit_dep=models.IntegerField()
        sam_rte=models.IntegerField(null=True)
        rec_strime=models.CharField(max_length=150)
        tdms_flag=models.CharField(max_length=150)
        file_path=models.CharField(max_length=150, null=True)
        daq_sam_rte=models.IntegerField(null=True)
        x_pixel=models.IntegerField(null=True)
        y_pixel=models.IntegerField(null=True)
        ip_cam_x_slop=models.IntegerField(null=True)
        ip_cam_y_slop=models.IntegerField(null=True)
        beam_wid=models.IntegerField(null=True)
        beam_hei=models.IntegerField(null=True)
        lp_data=models.CharField(max_length=150, null=True)
        lp_data_idx=models.IntegerField(null=True)
        lp_data_len=models.IntegerField(null=True)
        lp_data_file_path=models.CharField(max_length=150, null=True)
        img_data=models.CharField(max_length=150, null=True)
        img_idx=models.IntegerField(null=True)
        img_file_path=models.CharField(max_length=150, null=True)
        beam_pwr=models.CharField(max_length=150, null=True)
        beam_pwr_idx=models.IntegerField(null=True)
        beam_pwr_path=models.CharField(max_length=150, null=True)
        img_video_path=models.CharField(max_length=150, null=True)
        beam_video_path=models.CharField(max_length=150, null=True)
        video_path=models.CharField(max_length=150, null=True)
        reg_user=models.CharField(max_length=150)
        reg_dt=models.DateTimeField( auto_now=True)

class Noise(models.Model):
        ni_set_idx=models.AutoField(primary_key=True)
        data_set_idx = models.ForeignKey('Metadata', on_delete=models.CASCADE)
        ni_info=models.CharField(max_length=150, null=True)
        ni_bg_cate=models.CharField(max_length=150, null=True)
        ni_bg_sub_cate=models.CharField(max_length=150, null=True)
        ni_place=models.CharField(max_length=150, null=True)
        ni_bg_sdb=models.CharField(max_length=150, null=True)
        ni_bg_luf=models.CharField(max_length=150, null=True)
        ni_device=models.CharField(max_length=150, null=True)
        ni_len=models.IntegerField(null=True)


class Detail(models.Model):
        snd_set_idx=models.AutoField(primary_key=True)
        data_set_idx = models.ForeignKey('Metadata', on_delete=models.CASCADE)
        snd_info=models.CharField(max_length=150)
        snd_cate=models.CharField(max_length=150)
        snd_sub_cate=models.CharField(max_length=150)
        snd_cmnt=models.CharField(max_length=150)
        snd_place=models.CharField(max_length=150)
        snd_ni_db=models.CharField(max_length=150)
        snd_ni_luf=models.CharField(max_length=150)
        snd_srt_time=models.CharField(max_length=150)
        snd_end_time=models.CharField(max_length=150)
        snd_len=models.IntegerField(null=True)
        snd_device=models.CharField(max_length=150)
        snd_danger=models.CharField(max_length=150, null=True)
